name: build and release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
         file: Cargo.toml
        id: version_check
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./target/release/tmlapis
          tag_name: ${{ steps.version_check.outputs.releaseVersion }}
          name: Release v${{ steps.version_check.outputs.releaseVersion }}
          body: "# Changes\nTODO: Update before publish"
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
